### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by xpd259** [uglyDwarf/linuxtrack#101]
Hello me again:tada: 
are the mac building instructions up to-date?
https://github.com/uglyDwarf/linuxtrack/wiki/New-Build-Apple-Mac
I no longer have a Mac to test this so this is just copy of the old
guide with the svn swapped for git

**Comment by uglyDwarf** [comment]
Hi,
the instructions are outdated; I use Qt 4.7 I think (will check), you also need Cmake and the rest of needed things should be easy to find in the mac_build script (OpenCV, LibUSB, ...)...

One note though - I'm building it on OSX 10.6.8; when I tried on 10.8, wine was not working for some reason. I didn't investigate much further then, but I'll take a look at that soon (I still have the PS3Eye support in the works)... Another thing to note is, that I use relatively old Wine version; that is intentional - the NP's installer when working without a screen, it does its job silently, without bothering user and without me needing 1001 other libraries just to get it compiled...

I'll go through it and update the page...

Kind regards,

Michal

**Comment by xpd259** [comment]
Hiya,

that would explain why I had issues on my mac VM
I'm a total n00b when it comes to the mac so it may have failed due to
errors on my part.
I will try again later when I've got some time this weekend.



I'm feeling really bad for just kinda wading in and arranging the wiki
so I *hope* you don't mind, I can't code yet so it's my way of giving
something back


Kind regards,

Dick Thomas

**Comment by uglyDwarf** [comment]
Hi,
of course I don't mind - on the contrary; I wanted to attend to it for a looong time...

Just out of curiosity, might I ask you what mac VM do you use? I'm asking, because due to the budget reasons I had to resort to using a "Customac" (some call it hackintosh), but having OS X available in a VM (preferably on Linux), would be a huge help (especially when tuning something fishy)...
I saw some tricks on how to do that, but it involved mostly in using old VirtualBox, some prepatched OSX images (you can't trust that) or some hard patching of VMWare... I tried some others, but it didn't work at all.

I'm going through the build process now, so tomorrow I should have something ready...

Kind regards,

Michal

**Comment by xpd259** [comment]
I just happen to have bought a 10.5 dvd from Apple when I had a Mac and use
the Iboot.iso from tonymac
so its basically a hackintosh but using legitimate media not 'hacked' ones.
I use the iboot.iso to boot the DVD and install as normal only issue is I
have to keep the iso image in virtual-box.
I've not managed to upgrade it yet to anything newer but I've not tried as
I'm sure you know what life is like, something always gets in the way

DT

**Comment by uglyDwarf** [comment]
I also have the Snow Leopard DVD from times before my Mini died... I can try that too when I have some time...

Thank you for pointing me to it...

Kind regards,

Michal

**Comment by uglyDwarf** [comment]
The Mac install instructions are updated.

**Comment by borisrorsvort** [comment]
Any chance to investigate the mac build again?

**Comment by uglyDwarf** [comment]
Do you mean new MacOS X build (fixed El Capitan behavior), or the build instructions?

New build should be ready in the weekend...

And to build on Mac, I use the mac_build script, which puts all things together, but it is not very user friendly (it just builds the whole thing, but not much error checking yet). Another catch is, that I'm building it on 10.6; 10.8 caused some problems with wine...

Kind regards,

Michal

**Comment by borisrorsvort** [comment]
yeah I was trying on 10.10 then I found the build in the google code project which works but sadly not with Elite Dangerous. Any clue or tips about that ?

**Comment by uglyDwarf** [comment]
Hi,
the newest build is in the El Capitan issue, hopefully this weekend I'll be able to produce finally the 0.99.13... As for the Elite Dangerous, I'll respond in the new issue you created.

Kind regards,
Michal

**Comment by uglyDwarf** [comment]
Hello,
trying to reduce the issues backlog, I'm going to close this issue now.

Please let me know should you encounter any more problems...

Kind regards,

Michal
